<a href="https://colab.research.google.com/github/if164ever1/TensorFlow_Learning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#Introduction to Tensors

In [6]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.19.0


In [7]:
#Create a first Tensor
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
#Check the number of dimensions
scalar.ndim


0

In [9]:
#Create a vector
vector = tf.constant([42,13,32])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([42, 13, 32], dtype=int32)>

In [10]:
#Check the dimension of vector
vector.ndim

1

In [11]:
#Create a matrix
matrix = tf.constant([[12,3],
                      [34,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  3],
       [34,  5]], dtype=int32)>

In [14]:
matrix.ndim

2

In [19]:
#Create another matrix
another_matrix = tf.constant([[10., 74.], [3., 2.], [6., 5.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 74.],
       [ 3.,  2.],
       [ 6.,  5.]], dtype=float16)>

In [21]:
#Number of dimensions
another_matrix.ndim

2

In [44]:
#Create a tensor
tensor = tf.constant([
                      [ [1,2,3],[4,5,6] ],
                      [ [7,8,9], [11,12,13]] ,
                      [ [14,15,16], [17,18,19]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]],

       [[14, 15, 16],
        [17, 18, 19]]], dtype=int32)>

In [47]:
tensor.ndim

3

In [49]:
#Create Tensor with VAriable
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [54]:
changable_tensor[0].assign(77)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([77,  7], dtype=int32)>

In [58]:
#Create a random Tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [64]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)